import assert from 'node:assert/strict';
import { forward } from '../server/proxy.mjs';
const calls=[];
let upstreamStatus=200,offline=false;
globalThis.fetch=async(url,options)=>{calls.push({url,options});if(offline)throw new Error('unavailable');return new Response(upstreamStatus===204||upstreamStatus===304?null:JSON.stringify([{id:1}]),{status:upstreamStatus,headers:{'content-type':'application/json','cache-control':'no-cache'}});};
const request=(path,method='GET',body)=>new Request('https://example.pages.dev'+path,{method,headers:{apikey:'public-test-key',authorization:'Bearer public-test-key','content-type':'application/json',prefer:'return=representation'},...(body?{body:JSON.stringify(body)}:{})});
let res=await forward({request:request('/api/db/photos?select=*&order=id.desc'),params:{table:'photos'}},'db');
assert.equal(res.status,200);assert.equal(res.headers.get('cache-control'),'no-store');assert.equal(calls.at(-1).url,'https://okpcwsianqkouitdwhvx.supabase.co/rest/v1/photos?select=*&order=id.desc');assert.equal(calls.at(-1).options.headers.get('apikey'),'public-test-key');
res=await forward({request:request('/api/db/photos?id=eq.1','PATCH',{photo_date:'2026-09-23'}),params:{table:'photos'}},'db');assert.equal(res.status,200);assert.equal(calls.at(-1).options.method,'PATCH');assert.equal(await new Response(calls.at(-1).options.body).text(),'{"photo_date":"2026-09-23"}');
res=await forward({request:request('/api/db/photos','DELETE'),params:{table:'photos'}},'db');assert.equal(res.status,400);
res=await forward({request:request('/api/db/secrets'),params:{table:'secrets'}},'db');assert.equal(res.status,404);
res=await forward({request:new Request('https://example.pages.dev/api/db/photos'),params:{table:'photos'}},'db');assert.equal(res.status,401);
res=await forward({request:request('/media/photos/thumbnails/v1/image.jpg.webp'),params:{path:['thumbnails','v1','image.jpg.webp']}},'image');assert.equal(res.status,200);assert.equal(calls.at(-1).options.headers.has('apikey'),false);assert.match(res.headers.get('cache-control'),/31536000/);
upstreamStatus=404;res=await forward({request:request('/media/photos/missing.jpg'),params:{path:['missing.jpg']}},'image');assert.equal(res.status,404);assert.equal(res.headers.get('cache-control'),'no-store');
res=await forward({request:request('/media/photos/x.jpg','DELETE'),params:{path:['x.jpg']}},'image');assert.equal(res.status,405);
res=await forward({request:request('/media/photos/x.jpg'),params:{path:['..','x.jpg']}},'image');assert.equal(res.status,400);
res=await forward({request:request('/media/photos/x.html'),params:{path:['x.html']}},'image');assert.equal(res.status,400);
upstreamStatus=302;res=await forward({request:request('/media/photos/x.jpg'),params:{path:['x.jpg']}},'image');assert.equal(res.status,502);
offline=true;res=await forward({request:request('/api/db/photos'),params:{table:'photos'}},'db');assert.equal(res.status,502);assert.equal(res.headers.get('cache-control'),'no-store');
console.log('PASS: same-origin proxy preserves reads/writes, public credentials and response status; restricts tables/methods/paths; caches only successful images; reports upstream failures');
